### ISSUE TITLE
Saving model

### ISSUE THREAD

**Issue by evangeliazve** [kstathou/vector_engine#3]
Hello Mr. Stathoulopoulos,

Do you suggest any efficient way to save the training model results and easily reproduce the search engine with query ?

Thank you again for your help and support.

Best Regards,
Evangelia Zve

**Comment by kstathou** [comment]
Hi @evangeliazve, I assume you want to save the faiss index, right? You can do this with:

```python
import faiss
faiss.write_index(index, filename)
```

and read the index with:
```python
import faiss
index = faiss.read_index(filename)
```

Regarding your second question, you can deploy the search engine as a streamlit application following the instructions [here](https://github.com/kstathou/vector_engine#how-to-deploy-the-streamlit-app-locally-with-docker) (you will need to have docker installed). The [second part of the tutorial](https://towardsdatascience.com/how-to-deploy-a-semantic-search-engine-with-streamlit-and-docker-on-aws-elastic-beanstalk-42ddce0422f3) explains what the code does.

If you created an index with your data, it will be slightly more involved as you might need to modify the `app.py` a bit. In either case, you might find the last section in this [colab notebook](https://colab.research.google.com/drive/11WBCrwNzbNWN7QbMEwzy-8MZROOVQFnZ?usp=sharing) helpful. It shows how to query a pre-built index with a new query.

**Comment by evangeliazve** [comment]
Hello Kostas,

Thanks a lot for your reply. It worked. Efharisto poly 

I will check the second part as well and let you know if any questions.

Best Regards,

Evangelia

**Comment by kstathou** [comment]
Parakalo! 

I'm leaving this issue open in case you have questions on the second part. If not, feel free to close it.

**Comment by kstathou** [comment]
Closing this, feel free to reopen if needed.
