### ISSUE TITLE
Euclidean Distance threshold

### ISSUE THREAD

**Issue by evangeliazve** [kstathou/vector_engine#4]
Hello Mr. Stathoulopoulos,

I was wondering if there is any threshold for the L3 distance that allows to retrieve only consistent results. 

My question probably apply not only here, but you may have some insights that can help.

Thanks again for your support.

Best Regards,
Evangelia

**Comment by kstathou** [comment]
Hi @evangeliazve, I don't have a good response to that. I'd say it depends on the task and how you present information. Sometimes, it's even helpful to find the top N most similar results with Faiss and rerank them with another method.

**Comment by kstathou** [comment]
Closing this, feel free to reopen if needed.
